Fetch minimum JDK version from Jenkinsfile
jenkinsci/plugin-modernizer-tool pull request #201
Opened 2024-08-20 08:30 UTC by sridamul

Fetches the minimum JDK version from Jenkinsfile.
For eg: 
Login-theme-plugin Jenkinsfile
```
buildPlugin(
  useContainerAgent: true, // Set to `false` if you need to use Docker for containerized tests
  configurations: [
    [platform: 'linux', jdk: 21],
    [platform: 'windows', jdk: 17],
])
```
Fetches the min jdk (platform windows) which is `17`

![Screenshot 2024-08-20 135232](https://github.com/user-attachments/assets/f1a10fc3-aef4-4f25-b168-c37e175f2eed)

Now this JDK version can be used directly to compile and verify plugins if the Jenkinsfile is present.

### Testing done
Interactive testing + Unit tests

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-08-20 08:41 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/PluginMetadata.java
> +    private int jdkVersion;
Why an int when we have now an Enum for the JDK model ?
Why not getting list of JDK version configured at let the call (PluginModernizer) use they JDK they need (minimum or maximum)

2024-08-20 08:45 UTC, jonesbusy requested changes
Thanks for your PR. But there are few things wrong here that need to be fixed.

Also the code need to be maintainable and more easy to read

2024-08-20 08:45 UTC, jonesbusy commented on plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollectorTest.java
> +        assertEquals(0, jdkVersion);
Why not adding a file to the rewrite test or even writting new test ?

```
groovy(
        """
          buildPlugin()
        """,
        spec -> spec.path("Jenkinsfile")),
```

2024-08-22 06:23 UTC, jonesbusy requested changes

2024-08-22 06:23 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollector.java
> +        private JDK jdkVersion;
I think we should accumulate all JDK version found and not only the latest

2024-08-22 06:23 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollector.java
> +                                                                    if (currentJdkVersion < jdkVersion) {
This logic should not be there. It's the responsibility of the user of metadata to select the JDK version. The collector should be dumb as possible

2024-08-22 06:23 UTC, jonesbusy commented on plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollectorTest.java
> +                pomXml(
This test only check Jenkinsfile. Let's try to use a minimal pom. And if possible from a constant. Will make the test more easy to read

2024-08-22 06:23 UTC, jonesbusy commented on plugin-modernizer-core/src/test/java/io/jenkins/tools/pluginmodernizer/core/extractor/MetadataCollectorTest.java
> +    }
Missing some test with empty buildPlugin() or more outdated/exotic configuration.

For example how the visitors are reacting to https://github.com/jenkinsci/forensics-api-plugin/blob/main/Jenkinsfile

2024-08-22 06:36 UTC, sridamul commented
Hey @jonesbusy, Just now seen your reviews. Let me change accordingly. Thanks!

2024-08-22 07:48 UTC, sridamul commented
> Missing some test with empty buildPlugin() or more outdated/exotic configuration.
> 
> For example how the visitors are reacting to https://github.com/jenkinsci/forensics-api-plugin/blob/main/Jenkinsfile

Working on to update the logic, will raise new pr to cover this kind of file too.

2024-08-22 11:06 UTC, jonesbusy approved these changes

2024-08-22 11:06 UTC, jonesbusy commented
Thanks a lot! Merging, very happy to start testing this :)

2024-08-22 11:06 UTC, merged