Move plugin git directories to local cache
jenkinsci/plugin-modernizer-tool pull request #247
Opened 2024-08-31 15:14 UTC by jonesbusy

Fix #243

![Screenshot from 2024-08-31 16-53-41](https://github.com/user-attachments/assets/1ce5cf30-2d39-42bd-81c2-ea47da95930f)

### Testing done

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-08-31 16:50 UTC, sridamul approved these changes
FYI. There are some test errors in resolving the path correctly.

2024-09-01 03:48 UTC, jonesbusy commented
Thanks, fixing. I forget to run some tests

I've added a subfolder to avoid deleting the content of an arbitrary folder when specifying the --cache-path option

![Screenshot from 2024-09-01 05-45-29](https://github.com/user-attachments/assets/df14005b-fdf2-4068-ab12-c3a575d3f390)

Typically without this fix, using `--cache-path . --clean-local-data` would wipe your current directory.

By always using a subfolder when prevent such disaster

2024-09-01 04:11 UTC, sridamul requested changes

2024-09-01 04:11 UTC, sridamul commented on plugin-modernizer-cli/src/test/java/io/jenkins/tools/pluginmodernizer/cli/MainTest.java
> +        String[] args = {"-p", "plugin1,plugin2", "-r", "FetchMetadata", "--skip-push", "--skip-push"};
```suggestion
        String[] args = {"-p", "plugin1,plugin2", "-r", "FetchMetadata", "--skip-push"};
```

2024-09-01 04:15 UTC, sridamul approved these changes

2024-09-01 05:03 UTC, gounthar approved these changes

2024-09-01 05:28 UTC, merged