Add gh service
jenkinsci/plugin-modernizer-tool pull request #75
Opened 2024-07-13 13:08 UTC by sridamul

Added GH service class which allows us to fork and clone plugin, commit the changes (after transformation) and PR creation.

Note: GH token and username is passed through system env variables.

This is a rough PR, open to improvements. Thanks!

### Testing done
This [PR](https://github.com/sridamul/login-theme-plugin/pull/8) is automated with the tool starting from forking, cloning and PR creation

### Log file
```
Starting Plugin Modernizer 
Plugins: [login-theme-plugin] 
Recipes: [AddPluginsBom] 
Forking and cloning login-theme-plugin locally 
Forking the repository... 
Repository forked successfully 
Cloning login-theme-plugin 
Cloned successfully 
Invoking clean phase for plugin: login-theme-plugin 
Invoking rewrite plugin for plugin: login-theme-plugin 
Creating pull request for plugin: login-theme-plugin 
Changes committed 
Pushed changes to forked repository 
Pull request created: https://github.com/sridamul/login-theme-plugin/pull/8 
```

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2024-07-13 18:09 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
> +    private static final String GITHUB_TOKEN = System.getenv("GITHUB_TOKEN");
Why not on settings ? It would be better to centralise it here and pass it to contructor

2024-07-14 18:34 UTC, iamrajiv approved these changes

2024-07-15 03:45 UTC, jonesbusy requested changes

2024-07-15 03:45 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
> +            if (pr.getHead().getRef().equals(branchName) && pr.getTitle().equals(PR_TITLE)) {
Extract this to a private method and use javastream find()

2024-07-15 03:45 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
> +        String root = System.getProperty("user.dir");
Please use moderne Java with Paths and Path

2024-07-15 03:45 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
> +        File pluginDirectory = new File(Settings.TEST_PLUGINS_DIRECTORY + pluginName);
Please use modern Java with Paths and Path

2024-07-15 03:45 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/impl/PluginModernizer.java
> +        this.ghService = new GHService();
Config is not needed ? It's useful for the cache path and dry run option

Did we try with `--dry-run` ?

2024-07-15 03:46 UTC, jonesbusy commented
Some minor code issues/improvement and I think we can do ahead with this first integration with JGit/GitHub

Also don't forget to document on the README.md the new parameter of needed environment variables

2024-07-15 05:23 UTC, sridamul commented
Tested manually with dry run option.

2024-07-15 05:43 UTC, jonesbusy commented on plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/github/GHService.java
> +            LOG.info("Repository already forked.");
Can you please track an issue to ensure the GH repo is in sync with upstream. It should be possible via API

I'm using generally the `gh repo sync username/repo`

Without sync existing repo there is a risk to open branches from outdated main branch

2024-07-15 05:44 UTC, jonesbusy approved these changes

2024-07-15 05:57 UTC, merged